INSERT INTO `menu` (`uuid`, 
                    `name`,
                    `link`,
                    `parentid`,
                    `displayorder`,
                    `createdby`,
                    `modifiedby`,
                    `creationdate`,
                    `modifieddate`,
                    `roleid`)
            VALUES ('menu:40c340ca-880d-11e1-8b11-001d0962e8d9',
                    'Image Uploads',
                    '',
                    NULL,
                    2,
                    1,
                    1,
                    NOW(),
                    NOW(),
                    'role:5320db82-880e-11e1-b592-001d0962e8d9'
                    );
INSERT INTO `menu` (`uuid`,
                    `name`,
                    `link`,
                    `parentid`,
                    `displayorder`,
                    `createdby`,
                    `modifiedby`,
                    `creationdate`,
                    `modifieddate`,
                    `roleid`)
            VALUES ('menu:f5031cee-880e-11e1-acab-001d0962e8d9',
                    'Upload',
                    'modules/image_uploads/image_uploader.php',
                    'menu:40c340ca-880d-11e1-8b11-001d0962e8d9',
                    2,
                    1,
                    1,
                    NOW(),
                    NOW(),
                    'role:5320db82-880e-11e1-b592-001d0962e8d9'
                    );
