INSERT INTO `roles` (`uuid`, 
                    `name`,
                    `description`,
                    `inactive`,
                    `createdby`,
                    `creationdate`,
                    `modifiedby`,
                    `modifieddate`,
                    `custom1`,
                    `custom2`,
                    `custom3`,
                    `custom4`,
                    `custom5`,
                    `custom6`,
                    `custom7`,
                    `custom8`)
            VALUES ('role:5320db82-880e-11e1-b592-001d0962e8d9',
                    'image uploads',
                    'Mass upload images.',
                    '0',
                    1,
                    NOW(),
                    1,
                    NOW(),
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    '0',
                    '0'
                    );
