<?php

	$modules["netro_email"]["name"] = "Netro42 Order Email Import";
	
	$modules["netro_email"]["version"] = "0.10";
	
	$modules["netro_email"]["description"] = 
	"This module imports customer and order information from emails generated by Netro42 version of sheactive.co.uk.";
	
	$modules["netro_email"]["requirements"] = 
	"phpBMS Core v0.98 or greater; BMS module v0.98 or greater; phpBMS Scheduler activated through cron or other scheduling program.";

?>
