<?php

	$modules["bleep_email"]["name"] = "Bleep Upadtes Email Import";
	
	$modules["bleep_email"]["version"] = "0.10";
	
	$modules["bleep_email"]["description"] =
	"This module imports catalogue and stock information from emails generated by Bleep Server.";
	
	$modules["bleep_email"]["requirements"] =
	"phpBMS Core v0.98 or greater; BMS module v0.98 or greater; phpBMS Scheduler activated through cron or other scheduling program.";

?>
