INSERT INTO `menu` (`uuid`, 
                    `name`,
                    `link`,
                    `parentid`,
                    `displayorder`,
                    `createdby`,
                    `modifiedby`,
                    `creationdate`,
                    `modifieddate`,
                    `roleid`)
            VALUES ('menu:c7904768-9b42-11e1-90e0-dba2b709c097',
                    'Brochure Requests',
                    '',
                    NULL,
                    2,
                    1,
                    1,
                    NOW(),
                    NOW(),
                    'role:e21a7374-9b42-11e1-86ce-ffe76f1c2233'
                    );
INSERT INTO `menu` (`uuid`,
                    `name`,
                    `link`,
                    `parentid`,
                    `displayorder`,
                    `createdby`,
                    `modifiedby`,
                    `creationdate`,
                    `modifieddate`,
                    `roleid`)
            VALUES ('menu:0edabed2-9b43-11e1-a41f-bbce72a057d2',
                    'Upload Now',
                    'modules/brochure_requests/feed_uploader.php',
                    'menu:c7904768-9b42-11e1-90e0-dba2b709c097',
                    2,
                    1,
                    1,
                    NOW(),
                    NOW(),
                    'role:e21a7374-9b42-11e1-86ce-ffe76f1c2233'
                    );
