INSERT INTO `roles` (`uuid`, 
                    `name`,
                    `description`,
                    `inactive`,
                    `createdby`,
                    `creationdate`,
                    `modifiedby`,
                    `modifieddate`,
                    `custom1`,
                    `custom2`,
                    `custom3`,
                    `custom4`,
                    `custom5`,
                    `custom6`,
                    `custom7`,
                    `custom8`)
            VALUES ('role:e21a7374-9b42-11e1-86ce-ffe76f1c2233',
                    'brochure requests',
                    'Maintain Brochure Requests.',
                    '0',
                    1,
                    NOW(),
                    1,
                    NOW(),
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    '0',
                    '0'
                    );
