--
-- Table structure for table `attractive_categories`
--

DROP TABLE IF EXISTS `attractive_categories`;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `attractive_categories` (
  `id` int(10) unsigned NOT NULL DEFAULT '0',
  `name` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('1','Accueil');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('22','02.Activités');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('24','03.DANSE');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('25','04.RUNNING');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('75','Chaussures');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('14','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('15','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('16','03.SACS & ACCESS');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('28','04.LINGERIE');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('21','01.Produits');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('23','02.FITNESS GYM');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('8','Pantalons');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('13','02.CHAUSSURES');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('83','Vestes / Sweats');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('5','Vestes / Sweats');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('67','Mode - Converse');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('76','Sélection');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('77','T-shirts');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('111','Pantalons');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('79','Débardeurs');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('80','Pantacourt');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('81','Pantacourt');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('82','Pantalons');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('26','04.NATATION');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('27','OUTDOOR');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('31','Meilleures ventes à l\'accueil');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('32','Nouveautés à l\'accueil');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('69','01.STREET & MODE');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('73','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('72','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('74','Hauts manches courtes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('34','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('35','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('37','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('38','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('106','Sport - Running');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('39','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('40','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('41','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('42','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('43','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('44','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('70','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('45','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('46','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('47','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('48','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('49','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('50','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('51','03.YOGA PILATES');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('52','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('53','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('54','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('55','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('56','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('57','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('58','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('59','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('60','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('63','01.VETEMENTS');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('108','Sport - Fitness & Gym');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('109','Vestes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('110','Vestes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('64','Top Ten');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('65','Look du moment');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('66','Phares');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('100','A trier');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('103','Doudounes / Blousons');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('104','Débardeurs / Brassières');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('112','Corsaires');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('113','T-shirts manches courtes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('114','Débardeurs');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('115','Pantalons');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('116','T-shirts manches courtes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('117','Débardeurs');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('118','Doudounes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('119','Pantalons');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('120','Débardeurs');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('121','Hauts manches courtes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('122','Hauts manches longues');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('123','Vestes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('124','Pantacourt');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('125','Sac de Sport');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('126','Accessoires chaussures');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('163','Cosmétique');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('128','Chaussettes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('129','Nike +');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('130','Pochettes / bandeaux');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('131','Sac Mode');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('132','Vêtements pluie / froid');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('151','Mode - Adidas');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('136','Marche / ballade');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('137','Pantalons');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('138','Pantacourt et Shorts');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('139','Hauts manches courtes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('140','Hauts manches longues');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('141','Jupes / Robes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('142','Hauts manches longues');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('143','Nike');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('144','Shock Absorber');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('145','Casques audio');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('146','Vestes');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('147','Débardeurs');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('148','Ballerines');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('150','TENNIS');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('152','Mode - Nike');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('153','Mode - Freddy');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('154','Mode - Chipie');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('155','Mode - Fye');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('157','Mode - DKNY');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('158','Shorts');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('159','Shorts');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('160','Forme - FitFlop');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('162','Maillot de bain une pièce');
INSERT INTO `attractive_categories` (`id`, `name`) VALUES ('164','Mode - New Balance');

