INSERT INTO `roles` (`uuid`, 
                    `name`,
                    `description`,
                    `inactive`,
                    `createdby`,
                    `creationdate`,
                    `modifiedby`,
                    `modifieddate`,
                    `custom1`,
                    `custom2`,
                    `custom3`,
                    `custom4`,
                    `custom5`,
                    `custom6`,
                    `custom7`,
                    `custom8`)
            VALUES ('role:dbc4ff20-888d-11e1-aa23-001d0923519e',
                    'product feeds',
                    'Maintain product feeds.',
                    '0',
                    1,
                    NOW(),
                    1,
                    NOW(),
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    '0',
                    '0'
                    );
